# Generated by Django 2.2 on 2020-05-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquote', '0003_quote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Wall_Quote',
        ),
    ]
