# Generated by Django 2.2 on 2020-05-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userquote', '0005_wall_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_quote',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermessages', to='userquote.User'),
        ),
    ]
