# Generated by Django 2.2 on 2020-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquote', '0006_auto_20200504_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_quote',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='userquote.User'),
        ),
    ]
